### PR TITLE
Desafio Hurb - Alexandre Papanis

### PR DESCRIPTION
**Pull request by alexpapanis**
Esse PR se refere ao desafio proposto para o processo seletivo do Hurb.

### CODE REVIEW

**Comment by zanaca** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Comment by automator-hurb** [comment]
Thank you! Your code is being reviewed.

**Pull request closed without merging**
